# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0006_auto_20160928_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeapihttpauth',
            name='json_schema',
            field=models.TextField(default='{}', help_text='Default "{}", means no JSON Schema.', max_length=20480, verbose_name='JSON Schema'),
        ),
        migrations.AlterField(
            model_name='writeapiip',
            name='from_ip',
            field=models.TextField(default='127.0.0.1', help_text='Only accept requests from a IP in this list separated by whitespace . 0.0.0.0 means all.', max_length=2048, verbose_name='From IPs'),
        ),
        migrations.AlterField(
            model_name='writeapiip',
            name='json_schema',
            field=models.TextField(default='{}', help_text='Default "{}", means no JSON Schema.', max_length=20480, verbose_name='JSON Schema'),
        ),
        migrations.AlterField(
            model_name='writeapioauth2',
            name='json_schema',
            field=models.TextField(default='{}', help_text='Default "{}", means no JSON Schema.', max_length=20480, verbose_name='JSON Schema'),
        ),
    ]
