# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregations', '0002_auto_20160928_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregation',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='aggregation',
            name='execute_time_1',
            field=models.TimeField(help_text='Use 24 hour time. (e.g. 20:30:00 for 8:30 pm)', verbose_name='Execute Time'),
        ),
        migrations.AlterField(
            model_name='aggregation',
            name='output_collection_name',
            field=models.CharField(help_text='The resulting collection.\n        Do not include $out in your pipeline.', max_length=256),
        ),
        migrations.AlterField(
            model_name='aggregation',
            name='pipeline',
            field=models.TextField(default='[]', max_length=20480, verbose_name='Pipeline'),
        ),
    ]
