# Generated by Django 2.2.7 on 2019-11-29 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateHistory',
        ),
    ]
