# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-06 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('search', '0004_auto_20161006_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomHTTPAuthReadAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_format', models.CharField(choices=[(b'json', b'JSON'), (b'html', b'HTML'), (b'csv', b'Comma Separated Value (.csv)')], default=b'json', max_length=4)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('query', models.TextField(default=b'{}', max_length=2048, verbose_name=b'JSON Query')),
                ('type_mapper', models.TextField(default=b'{}', max_length=2048, verbose_name='Map non-string variables to numbers or Boolean')),
                ('sort', models.TextField(blank=True, default=b'', help_text=b'e.g. [["somefield", 1], ["someotherfield", -1] ]', max_length=2048, verbose_name=b'Sort Dict')),
                ('return_keys', models.TextField(blank=True, default=b'', help_text='Default is blank which returns all keys. Separate keys by white space to limitthe keys that are returned.', max_length=2048)),
                ('default_limit', models.IntegerField(default=200, help_text=b'Limit results to this number unless specified otherwise.')),
                ('database_name', models.CharField(max_length=100)),
                ('collection_name', models.CharField(max_length=100)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'ordering': ('-creation_date',),
                'get_latest_by': 'creation_date',
                'verbose_name_plural': 'CustomHTTPAuthReadAPI',
            },
        ),
        migrations.CreateModel(
            name='CustomPublicReadAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_format', models.CharField(choices=[(b'json', b'JSON'), (b'html', b'HTML'), (b'csv', b'Comma Separated Value (.csv)')], default=b'json', max_length=4)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('query', models.TextField(default=b'{}', max_length=2048, verbose_name=b'JSON Query')),
                ('type_mapper', models.TextField(default=b'{}', max_length=2048, verbose_name='Map non-string variables to numbers or Boolean')),
                ('sort', models.TextField(blank=True, default=b'', help_text=b'e.g. [["somefield", 1], ["someotherfield", -1] ]', max_length=2048, verbose_name=b'Sort Dict')),
                ('return_keys', models.TextField(blank=True, default=b'', help_text='Default is blank which returns all keys. Separate keys by white space to limitthe keys that are returned.', max_length=2048)),
                ('default_limit', models.IntegerField(default=200, help_text=b'Limit results to this number unless specified otherwise.')),
                ('database_name', models.CharField(max_length=100)),
                ('collection_name', models.CharField(max_length=100)),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-creation_date',),
                'get_latest_by': 'creation_date',
                'verbose_name_plural': 'CustomPublicReadAPI',
            },
        ),
        migrations.RemoveField(
            model_name='savedsearch',
            name='group',
        ),
        migrations.RemoveField(
            model_name='savedsearch',
            name='user',
        ),
        migrations.DeleteModel(
            name='SavedSearch',
        ),
    ]
