# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20161006_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customhttpauthreadapi',
            options={'get_latest_by': 'creation_date', 'ordering': ('-creation_date',)},
        ),
        migrations.AlterModelOptions(
            name='custompublicreadapi',
            options={'get_latest_by': 'creation_date', 'ordering': ('-creation_date',)},
        ),
        migrations.AlterModelOptions(
            name='httpauthreadapi',
            options={},
        ),
        migrations.AlterModelOptions(
            name='publicreadapi',
            options={},
        ),
        migrations.AlterField(
            model_name='customhttpauthreadapi',
            name='default_limit',
            field=models.IntegerField(default=200, help_text='Limit results to this number unless specified otherwise.'),
        ),
        migrations.AlterField(
            model_name='customhttpauthreadapi',
            name='output_format',
            field=models.CharField(choices=[('json', 'JSON'), ('html', 'HTML'), ('csv', 'Comma Separated Value (.csv)')], default='json', max_length=4),
        ),
        migrations.AlterField(
            model_name='customhttpauthreadapi',
            name='query',
            field=models.TextField(default='{}', max_length=2048, verbose_name='JSON Query'),
        ),
        migrations.AlterField(
            model_name='customhttpauthreadapi',
            name='return_keys',
            field=models.TextField(blank=True, default='', help_text='Default is blank which returns all keys. Separate keys by white space to limitthe keys that are returned.', max_length=2048),
        ),
        migrations.AlterField(
            model_name='customhttpauthreadapi',
            name='slug',
            field=models.SlugField(help_text='Give your API a unique name', max_length=100),
        ),
        migrations.AlterField(
            model_name='customhttpauthreadapi',
            name='sort',
            field=models.TextField(blank=True, default='', help_text='e.g. [["somefield", 1], ["someotherfield", -1] ]', max_length=2048, verbose_name='Sort Dict'),
        ),
        migrations.AlterField(
            model_name='customhttpauthreadapi',
            name='type_mapper',
            field=models.TextField(default='{}', max_length=2048, verbose_name='Map non-string variables to numbers or Boolean'),
        ),
        migrations.AlterField(
            model_name='custompublicreadapi',
            name='default_limit',
            field=models.IntegerField(default=200, help_text='Limit results to this number unless specified otherwise.'),
        ),
        migrations.AlterField(
            model_name='custompublicreadapi',
            name='output_format',
            field=models.CharField(choices=[('json', 'JSON'), ('html', 'HTML'), ('csv', 'Comma Separated Value (.csv)')], default='json', max_length=4),
        ),
        migrations.AlterField(
            model_name='custompublicreadapi',
            name='query',
            field=models.TextField(default='{}', max_length=2048, verbose_name='JSON Query'),
        ),
        migrations.AlterField(
            model_name='custompublicreadapi',
            name='return_keys',
            field=models.TextField(blank=True, default='', help_text='Default is blank which returns all keys. Separate keys by white space to limitthe keys that are returned.', max_length=2048),
        ),
        migrations.AlterField(
            model_name='custompublicreadapi',
            name='slug',
            field=models.SlugField(help_text='Give your API a unique name', max_length=100),
        ),
        migrations.AlterField(
            model_name='custompublicreadapi',
            name='sort',
            field=models.TextField(blank=True, default='', help_text='e.g. [["somefield", 1], ["someotherfield", -1] ]', max_length=2048, verbose_name='Sort Dict'),
        ),
        migrations.AlterField(
            model_name='custompublicreadapi',
            name='type_mapper',
            field=models.TextField(default='{}', max_length=2048, verbose_name='Map non-string variables to numbers or Boolean'),
        ),
        migrations.AlterField(
            model_name='httpauthreadapi',
            name='search_keys',
            field=models.TextField(blank=True, default='', help_text='The default, blank, returns\n                                                all keys. Providing a list of\n                                                keys, separated by whitespace,\n                                                limits the API search to only\n                                                these keys.', max_length=4096),
        ),
        migrations.AlterField(
            model_name='httpauthreadapi',
            name='slug',
            field=models.SlugField(help_text='Give your API a unique name', max_length=100),
        ),
        migrations.AlterField(
            model_name='publicreadapi',
            name='search_keys',
            field=models.TextField(blank=True, default='', help_text='The default, blank, returns\n                                                all keys. Providing a list of\n                                                keys, separated by whitespace,\n                                                limits the API search to only\n                                                these keys.', max_length=4096),
        ),
        migrations.AlterField(
            model_name='publicreadapi',
            name='slug',
            field=models.SlugField(help_text='Give your API a unique name', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='httpauthreadapi',
            unique_together=set([('database_name', 'collection_name', 'slug')]),
        ),
        migrations.AlterUniqueTogether(
            name='publicreadapi',
            unique_together=set([('database_name', 'collection_name', 'slug')]),
        ),
    ]
